poolName: "thumbd"
accept:
# Use all drives mounted via USB
- pathContains: "usb2"
deviceSpec:
  filesystem: ext4
  # Tune the filesystem for large files and disable journaling (unsafe!) to speed up provision and writes
  mkfsOptions: ["-T", "largefile4", "-O", "^has_journal"]
poolSpec:
  # Directory to mount the thumb drives
  deviceMountPath: mergerfs-devices/
  # MergerFS filesystem to join the drives
  mergerFSMountPath: mergerfs-target/
  directories:
  # On each thumbdrive, create a directory foobar owned by user:wheel
  - name: foobar